Exception on /accountSetting [POST]
Traceback (most recent call last):
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\DashboardProject\auth.py", line 69, in accountSetting
    user.password = generate_password_hash(newpass, method='sha256')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\venv\Lib\site-packages\werkzeug\security.py", line 101, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leosc\Documents\GitHub\bluebuffalo\venv\Lib\site-packages\werkzeug\security.py", line 66, in _hash_internal
    raise ValueError(f"Invalid hash method '{method}'.")
ValueError: Invalid hash method 'sha256'.
